version: '3.7'

services:
  app:
    image: 'apeczka:latest'
    container_name: finalProject
    restart: always
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    networks:
      - app-net

  postgresql:
    image: 'postgres:latest'
    container_name: finalprojectsql
    restart: always
    ports:
      - "5433:5432"
    networks:
      - app-net
    environment:
      - 'POSTGRES_ROOT_PASSWORD=#Mati1991'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=#Mati1991'

networks:
  app-net:
    driver: bridge

